phases:
################################################################################
- phase: Default
################################################################################
  displayName: Linux Agent
  steps:

  # Clean
  - checkout: self
    clean: true

  - task: Maven@2
    displayName: Maven pom.xml

  - task: CopyFiles@2
    displayName: Copy Files to: 
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**/*.jar'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact: drop
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'

